---

  - name: install docker on RedHat
    yum: name={{item}} state=latest
    with_items:
      - docker
      - docker-python

#  - name: Install easy_install package
#    yum: name={{item}} state=latest
#    with_items:
#      - python-setuptools

#  # We must install pip before we can use the pip module below
#  - easy_install: name=pip #state=latest required ansible 2.x
#
#  # Install latest version when no specific release is set.
#  - name: Upgrade latest pip, setuptools, and docker-py with pip
#    pip:
#      name: "{{ item.name }}"
#      state: latest
#    with_items:
#      - { name: pip, version: "{{ pip_version_pip }}" }
#      - { name: setuptools, version: "{{ pip_version_setuptools }}" }
#      - { name: docker-py, version: "{{ pip_version_docker_py }}" }
#    when: item.version=="latest"

#  # Install specific version when set in the variables
#  - name: Install specific pip, setuptools, and docker-py with pip
#    pip:
#      name: "{{ item.name }}"
#      state: present
#      version: "{{ item.version }}"
#    with_items:
#      - { name: pip, version: "{{ pip_version_pip }}" }
#      - { name: setuptools, version: "{{ pip_version_setuptools }}" }
#      - { name: docker-py, version: "{{ pip_version_docker_py }}" }
#    when: item.version!="latest"

  - name: Enable Docker service on boot
    service: name=docker enabled=yes

  - name: Start the Docker daemon
    service: name=docker state=started
